# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  coreFeDartDir: core_fe_dart
  coreFeFlutterDir: core_fe_flutter
  coreFeInfrastructureDir: core_fe_infrastructure
  coreFePresentationDir: core_fe_presentation

trigger:
  - master
  - develop
  - azure-pipelines/*

pool:
  vmImage: "windows-latest"

jobs:
  - job: Tests
    steps:
    - task: FlutterInstall@0
    - task: FlutterTest@0
      displayName: Core.FE.Dart tests
      inputs:
        projectDirectory: $(coreFeDartDir)
    - task: FlutterTest@0
      displayName: Core.FE.Flutter tests
      inputs:
        projectDirectory: $(coreFeFlutterDir)
    - task: FlutterTest@0
      displayName: Core.FE.Infrastructure tests
      inputs:
        projectDirectory: $(coreFeInfrastructureDir)
    - task: FlutterTest@0
      displayName: Core.FE.Presentation tests
      inputs:
        projectDirectory: $(coreFePresentationDir)
    # - task: Bash@3
    #   displayName: Code Coverage
    #   inputs:
    #     filePath: '$(System.DefaultWorkingDirectory)/code-coverage.sh'
    # - task: Bash@3
    #   displayName: Upload test reports to codecov
    #   inputs:
    #     targetType: 'inline'
    #     script: 'bash <(curl -s https://codecov.io/bash) -t $(CORE_FE_COV)'
