name: core_fe_dart
description: Shared utilities layer to all layers across the application, it's
  framework independent
version: 0.1.1
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  equatable: ^2.0.3
  rxdart: ^0.27.2
  string_validator: ^0.3.0
  tuple: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
