name: core_fe_dart
description: Shared utilities layer to all layers across the application, it's
  framework independent
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  equatable: ^1.2.6
  rxdart: ^0.25.0
  string_validator: ^0.1.4
  tuple: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.9.0
